export const CUSTOMER_LOGIN_REQUEST = 'CUSTOMER_LOGIN_REQUEST'
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS'
export const CUSTOMER_LOGIN_FAILURE = 'CUSTOMER_LOGIN_FAILURE'

export const CUSTOMER_REGISTER_REQUEST = 'CUSTOMER_REGISTER_REQUEST'
export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS'
export const CUSTOMER_REGISTER_FAILURE = 'CUSTOMER_REGISTER_FAILURE'

export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST'
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS'
export const RESTAURANT_LOGIN_FAILURE = 'RESTAURANT_LOGIN_FAILURE'

export const RESTAURANT_REGISTER_REQUEST = 'RESTAURANT_REGISTER_REQUEST'
export const RESTAURANT_REGISTER_SUCCESS = 'RESTAURANT_REGISTER_SUCCESS'
export const RESTAURANT_REGISTER_FAILURE = 'RESTAURANT_REGISTER_FAILURE'

export const DISH_IMAGE_UPLOAD_REQUEST = "DISH_IMAGE_UPLOAD_REQUEST"
export const DISH_IMAGE_UPLOAD_SUCCESS = "DISH_IMAGE_UPLOAD_SUCCESS"
export const DISH_IMAGE_UPLOAD_FAILURE = "DISH_IMAGE_UPLOAD_FAILURE"

export const DISH_IMAGE_DELETE_SUCCESS = "DISH_IMAGE_DELETE_SUCCESS"
export const DISH_IMAGE_DELETE_REQUEST = "DISH_IMAGE_DELETE_REQUEST"
export const DISH_IMAGE_DELETE_FAILURE = "DISH_IMAGE_DELETE_FAILURE"

export const DISH_CREATE_SUCCESS = "DISH_CREATE_SUCCESS"
export const DISH_DELETE_SUCCESS = "DISH_DELETE_SUCCESS"

export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT"
export const RESTAURANT_LOGOUT = "RESTAURANT_LOGOUT"

export const SET_LOCATION = "SET_LOCATION" 
export const SET_DISH_TYPE = "SET_DISH_TYPE" 
export const SET_DELIVERY_TYPE = "SET_DELIVERY_TYPE"
export const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD"

